### PR TITLE
fixing css class for fu**ing bootstrap

### PR DESCRIPTION
**Pull request by e-riff**

### CODE REVIEW

**Review by MaxenceCodeFR — APPROVED** [review]
ENFIN !

**Review by Aelex51 — APPROVED** [review]

**Review by MaxenceCodeFR — APPROVED** [review]
Alé Lou Ya

**Review by MaxenceCodeFR — APPROVED** [review]
OKI

**Review by MaxenceCodeFR — APPROVED** [review]
Oui

**Review by jfm-wcs — APPROVED** [review]

**Pull request merged**
